### ISSUE TITLE
Cohere gives a NaN error

### ISSUE THREAD

**Issue by dzhigaevd** [AdvancedPhotonSource/cohere#2]
When the reconstruction routine starts Cohere says there is a nan element in the data (however, there is none).
After restarting the reconstruction, the error disappears. This issue make GA to fail since the first reconstruction is missing

Example from terminal:

starting reconstruction
data shape (256, 256, 120)
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 10, Driver: 460.39
[0] Quadro P4000, 8098 MB, CUDA Compute 6.1
Set deviceId 0
initialized
------- current iteration 0, error -nan -------
the image array has NaN element, quiting this reconstruction process
the reconstruction in c++ module encountered problems
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 10, Driver: 460.39
[0] Quadro P4000, 8098 MB, CUDA Compute 6.1
Set deviceId 0
initialized
------- current iteration 0, error 23718434822749864.000000 -------
------- current iteration 20, error 0.233417 -------

**Comment by DzhigaevD** [comment]
It fails even with example data in the package

**Comment by DzhigaevD** [comment]
Looks like it appears only if several scans are stacked for the reconstruction data

**Comment by bfrosik** [comment]
The reconstruction is checking now for the NaN and failing gracefully. In GA scenario the failed reconstruction is removed from population.
