### ISSUE TITLE
Ideas for improving Feature()

### ISSUE THREAD

**Issue by jacione** [AdvancedPhotonSource/cohere#23]
I’ve had several ideas that might make cohere a lot more versatile/readable with its algorithm sequences.

First, I know you recently added the dot notation for the algorithm sequence. However, I understand this only works with trigger sequences, not parameters (e.g. you can't have SW0 and SW1 with different thresholds). It might make more sense to define the features themselves in the config file, something like:
```python
algorithm_sequence = "3*(80*HIO.SW0+20*ER.SW0)+100*ER.SW1"
SW0 = ShrinkWrap(sw_type="GAUSS", threshold=0.2, sigma=1.0, trigger_every=1)
SW1 = ShrinkWrap(sw_type="GAUSS", threshold=0.1, sigma=2.0, trigger_every=3)
```

Second, rather than making a unique attribute in the `Rec` (or `CoupledRec`) class for each feature, there could just be a single dictionary attribute, which would be referenced by the keys given in the config file. For example, rather than `self.shrink_wrap_obj`, you would use `self.features["SW0"]`. The `self.features` attribute could be passed to `op_flow.py` to figure out the triggers.

Third, if we defined a `__call__()` method for the `Feature` class, it would make it more object-oriented (which is not _necessarily_ better, but it's worth considering).

Finally, what if the triggers were built into the `Feature` objects themselves (such as the `trigger_every` kwarg above). You could then have something like:
```python
def __call__(self):
    if self.x == self.trigger_every:
        self.apply_trigger()
        self.x = 0
    else:
        self.x += 1
```
Then, rather than worrying about getting the flow right, you just call every feature at every iteration. The counter increments until it hits a given value, then calls the trigger and resets. Since the start and stop would be defined in `algorithm_sequence`, this could potentially replace the entire trigger notation in the config file. Personally, I think it would be a lot more intuitive for new users.

I think these changes could make it _a lot_ easier to add new features in the future. However, they would also involve a lot of work. I also think backward-compatibility might be difficult if we change how the config file works, so that's something else to consider. Anyway, I wanted to run these ideas by you and see what you think before I start making big changes on my own fork.

**Comment by bfrosik** [comment]
1. The sub-triggers define sub-feature, and thus the parameters for each sub-trigger/sub-feature are different, as suggested. It is explained in docs. The configuration is different then suggested, as the list of values is configured for each parameter.
2. It is easier to maintain if objects are referenced as objects, not a value from dictionary. The dictionary would add another level of complexity.
3. The __call()__ can be implemented for the Feature class later, as it is a cosmetic issue. Right now all is encapsulated and working.
4. The cohere reconstruction is coded for performance. A good outcome was achieved by determining the running sequence at initialization. The proposed __call()__ function adds decisions, and therefore was not considered in the design. New comments were added to op_flow.py file to explain the design.
