### ISSUE TITLE
Improved exception handling

### ISSUE THREAD

**Issue by jacione** [AdvancedPhotonSource/cohere#34]
Cohere seems to handle most exceptions by printing that something happened and then just trying to power through. I think in many cases it would be better to let it crash so that you can at least get a traceback.

**Comment by bfrosik** [comment]
This would make sense in a single reconstruction case, also multipeak.
For GA the cohere starts with multiple processes and if one is not successful, it gracefully closes this process and continues with the rest. 
The verifier is supposed to catch problems with the configuration. We need to add verification for mp parameters.
Besides the incorrect parameters, other problems can happen. We can print the exception text in addition to the print that is currently there.

**Comment by jacione** [comment]
The problem that I've run into with just printing the exception text is that I have no idea when or where it went wrong.

**Comment by bfrosik** [comment]
I will add --debug option that will not handle exception.

**Comment by jacione** [comment]
Perhaps the graceful closing could just be in the GA manager, rather than across the board?

**Comment by bfrosik** [comment]
The --debug optional parameter has been added to the scripts that provide total solution from beamline preprocess to beamline visualization. Cohere phasing gets --debug in **kwargs and the code will not handle exception if debug is True.
The deug option is available to the developer in other scenarios.
